main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('pantries/', views.pantry_index, name='pantries'),
    path('pantries/<int:pk>/', views.pantry_detail, name='detail'),
    path('pantries/create/', views.PantryCreate.as_view(), name='pantries_create'),
    path('pantries/<int:pk>/update/', views.PantryUpdate.as_view(), name='pantries_update'),
    path('pantries/<int:pk>/delete/', views.PantryDelete.as_view(), name='pantries_delete'),
    path('pantries/<int:pk>/add_schedule/', views.add_schedule, name='add_schedule'),
    path('foods/', views.FoodList.as_view(), name='foods_index'),
    path('foods/<int:pk>/', views.FoodDetail.as_view(), name='foods_detail'),
    path('foods/create/', views.FoodCreate.as_view(), name='foods_create'),
    path('foods/<int:pk>/update/', views.FoodUpdate.as_view(), name='foods_update'),
    path('foods/<int:pk>/delete/', views.FoodDelete.as_view(), name='foods_delete'),
    path('pantries/<int:pantry_id>/assoc_food/<int:food_id>/', views.assoc_food, name='assoc_food'),
    path('pantries/<int:pantry_id>/unassoc_food/<int:food_id>/', views.unassoc_food, name='unassoc_food'),
    path('accounts/signup/', views.signup, name='signup'),
]

raam/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

SERVICES = (
    ('P', 'Pick Up'),
    ('D', 'Drop Off'),
)


class Food(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=20)
    quantity = models.IntegerField()

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('foods_detail', kwargs={'pk': self.id})



class Pantry(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    location = models.TextField(max_length=250)
    foods = models.ManyToManyField(Food)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.id})



    


class Schedule(models.Model):
    service = models.CharField(
        max_length=1,
        choices= SERVICES,
        default=SERVICES[0][0],
    )
    date = models.DateField('Schedule Date')

    pantry = models.ForeignKey(Pantry, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_service_display()} on {self.date}'

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Schedule

class ScheduleForm(ModelForm):
  class Meta:
    model = Schedule
    fields = ['date', 'service']

main_app/views.py
from django.shortcuts import redirect, render
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView, ListView
from .models import Pantry, Food
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ScheduleForm



def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def pantry_index(request):
    pantries = Pantry.objects.all()
    return render(request, 'pantries/index.html', { 'pantries': pantries })

def pantry_detail(request, pk):
    pantry = Pantry.objects.get(id=pk)
    schedule_form = ScheduleForm()

    foods_pantry_doesnt_have = Food.objects.exclude(
        id__in=pantry.foods.all().values_list('id'))
    
    
    return render(
        request, 
        'pantries/detail.html', {
            'pantry': pantry, 
            'schedule_form': schedule_form,
            'foods': foods_pantry_doesnt_have
        })

@login_required
def add_schedule(request, pk):
    form = ScheduleForm(request.POST)
    print(form._errors)
    if form.is_valid():
        new_schedule = form.save(commit=False)
        new_schedule.pantry_id = pk
        new_schedule.save()
    return redirect('detail', pk=pk)

@login_required
def assoc_food(request, pantry_id, food_id):
    Pantry.objects.get(id=pantry_id).foods.add(food_id)
    return redirect('detail', pk=pantry_id)

@login_required
def unassoc_food(request, pantry_id, food_id):
    Pantry.objects.get(id=pantry_id).foods.remove(food_id)
    return redirect('detail', pk=pantry_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('pantries')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


class PantryCreate(LoginRequiredMixin, CreateView):
    model = Pantry
    fields = ('name', 'location', 'description')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PantryUpdate(LoginRequiredMixin, UpdateView):
    model = Pantry
    fields = ('name', 'location', 'description')

class PantryDelete(LoginRequiredMixin, DeleteView):
    model = Pantry
    success_url = '/pantries/'


class FoodList(ListView):
    model = Food
    template_name = 'main_app/food_list.html'
class FoodDetail(LoginRequiredMixin, DetailView):
    model = Food
    template_name = 'main_app/food_detail.html'

class FoodCreate(LoginRequiredMixin, CreateView):
    model = Food
    fields = '__all__'
class FoodUpdate(LoginRequiredMixin, UpdateView):
    model = Food
    fields = ['name', 'description', 'quantity']
class FoodDelete(LoginRequiredMixin, DeleteView):
    model = Food
    success_url = '/foods/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<div>
  <div class="container">
    <div class="row">
      <h1>Our Mission</h1>
    </div>

    <div>
      <h4>
        “Here at RAAM we believe that real change begins within a community
        itself. RAAM was created to assist communities in tackling the issue of
        hunger with a more “grass-roots” approach.”
      </h4>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <h1>About RAAM</h1>
    </div>

    <div>
      <p>
        RAAM is a web application that allows users "RAAMERS" to create and
        manage their own personal Public Pantry.
      </p>
      <p>
        RAAM's goal is to help communities tackle the issue of hunger that
        affects over 41 million Americans, including 12 million children.”
      </p>
      <p>
        RAAM is a project that was created by a group of students at the General
        Assembly.
      </p>
      <p>RAAM was created by:</p>
    </div>
  </div>

  <div class="container">
    <div class="section">
      <div class="row">
        <div><h1 class="center">The Team</h1></div>
      </div>

      <!--   Team Section   -->
      <div class="row">
        <div class="col s12 m6">
          <div class="icon-block">
            <div class="center">
              <img
                style="width: 45%; border-radius: 50%"
                src="https://ca.slack-edge.com/T0351JZQ0-U027LLLM7UJ-eab10865c17a-512"
                alt=""
                srcset=""
              />
            </div>
            <h3 class="center orange-text text-darken-1">
              <a
                class="orange-text text-darken-1"
                href="https://github.com/CahylA1"
                >Cahyl</a
              >
            </h3>
            <h5 class="center">Front-End Engineer</h5>

            <p class="light">
              I am a highly motivated Software Developer who is inspired to
              become the best in my position . Working on my craft and aiming to
              be at the highest level of capability is always a goal for me .
              Peers would say that I am a critical thinker and when it comes to
              problem-solving I always find a way.
            </p>
          </div>
        </div>

        <div class="col s12 m6">
          <div class="icon-block">
            <div class="center">
              <img
                style="width: 40%; border-radius: 50%"
                src="https://ca.slack-edge.com/T0351JZQ0-U02CE959ZS8-d6c3248c03f6-512"
                alt=""
                srcset=""
              />
            </div>
            <h3 class="center orange-text text-darken-1">
              <a
                class="orange-text text-darken-1"
                href="https://github.com/chencho806"
                >Corey</a
              >
            </h3>
            <h5 class="center">Back-End Engineer</h5>
            <p class="light">
              A creative individual and team player with a unique perspective
              geared towards high level problem solving.
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col s12 m6">
          <div class="icon-block">
            <div class="center">
              <img
                style="width: 45%; border-radius: 50%"
                src="https://ca.slack-edge.com/T0351JZQ0-U02C42NDY77-3af373ed0a7a-512"
                alt=""
                srcset=""
              />
            </div>
            <h3 class="center orange-text text-darken-1">
              <a
                class="orange-text text-darken-1"
                href="https://github.com/mariorojasac"
                >Mario</a
              >
            </h3>
            <h5 class="center">Front-End Engineer</h5>

            <p class="light">
              Former Insurance Agent turned software engineer offering a strong
              foundation in Software Engineering principles across multiple
              platforms. Experienced in Html, CSS, and JavaScript.
            </p>
          </div>
        </div>

        <div class="col s12 m6">
          <div class="icon-block">
            <div class="center">
              <img
                style="width: 45%; border-radius: 50%"
                src="https://ca.slack-edge.com/T0351JZQ0-U02CLMAUSUR-68fc22a5f240-512"
                alt=""
                srcset=""
              />
            </div>
            <h3 class="center orange-text text-darken-1">
              <a
                class="orange-text text-darken-1"
                href="https://github.com/VernellMiller"
                >Vernell</a
              >
            </h3>
            <h5 class="center">Back-End Engineer</h5>

            <p class="light">
              Hello! I am Vernell Miller, an Atlanta-based Full Stack Engineer |
              2D/3D Graphic Designer with a background in Game Development and
              Design. I am an exceptional team player, and I strongly believe in
              the words of Japanese Author - Ryunosuke Satoro, “Individually, we
              are one drop. Together, we are an ocean.”
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row center">
      <h1>Contact Us</h1>
    </div>

    <div class="row">
      <div class="col s12 m6">
        <p>Email: info@raam.com</p>
        <p>Phone: (519) 888-8888</p>
        <p>Address: 123 Fake Street, city, state 46215</p>
      </div>
      <div class="col s12 m6">
        <p>Twitter: info@raam.com</p>
        <p>Instagram: @raam</p>
        <p>Tiktok: @raamofficial</p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>raam.com</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300&display=swap" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header>
      <nav class="white">
            <div class="nav-wrapper">
                <ul>
                    <li><a href="{% url 'home' %}" class="left brand-logo black-text"><img src="https://i.imgur.com/e8QVKVh.jpeg" width=60 height="55"></a></li>
                    <li><a href="{% url 'home' %}" class="center brand-logo orange-text darken-1 hide-on-med-and-down">RAAM</a></li>
                </ul>
                <ul class="right">
                  {% if user.is_authenticated %}
                  <li><a href="{% url 'pantries' %}" class="black-text">All Pantries</a></li>
                  <li><a href="{% url 'foods_index' %}" class="black-text">View All Foods</a></li>
                  <li><a href="{% url 'pantries_create'%}" class="black-text">Add Pantry</a></li>
                  <li><a href="{% url 'foods_create' %}" class="black-text">Add Food</a></li>
                  <li><a href="{% url 'about' %}" class="black-text">About</a></li>
                  <li><a href="{% url 'logout' %}" class="black-text">Logout</a></li>
                  {% else %}
                  <li><a href="{% url 'pantries' %}" class="black-text">All Pantries</a></li>
                  <li><a href="{% url 'about' %}" class="black-text">About</a></li>
                    <li><a href="{% url 'login' %}" class="black-text">Login</a></li>
                    <li><a href="{% url 'signup' %}" class="black-text">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
      </nav>
    </header>
    <main>
        {% block content %} 
        {% endblock %}
    </main>
    <footer class="page-footer white">
      <div class="footer-copyright">
            <div class="container center black-text">
            © 2021 Copyright RAAM
            </div>
          </div>
    </footer>
  </body>
</html> 

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br /><br />
      <h1
        class="header center orange-text text-darken-2"
        style="
          font-size: 5rem;
          font-weight: 600;
          text-shadow: 1px 1px 2px black, -1px -1px 2px black;
        "
      >
        Welcome To RAAM
      </h1>
      <div class="row center">
        <h5
          class="header col s12 light white-text"
          style="
            font-size: 5rem;
            font-weight: 600;
            text-shadow: 1px 1px 2px black, -1px -1px 2px black;
          "
        >
          One Community
        </h5>
      </div>
      <div class="row center">
        <a
          href="{% url 'pantries' %}"
          id="download-button"
          class="btn-large waves-effect waves-light orange darken-1"
          >Open Pantry</a
        >
      </div>
      <br /><br />
    </div>
  </div>
  <div class="parallax">
    <img
      src="https://cdn.shopify.com/s/files/1/0407/1801/products/DeepEtchVegImage_1600px_1.jpg?v=1624490545"
      alt="Unsplashed background img 1"
      style="transform: translate3d(-50%, 54.5rem, 0); opacity: 1"
    />
  </div>
</div>
<div class="container" style="padding: 5rem">
  <h3 class="orange-text text-darken-1">REAL</h3>
  <h3>CHANGE WITH</h3>
  <h3>A MORE</h3>
  <h3 class="orange-text text-darken-1">GRASS ROOTS</h3>
  <h3>APPROACH</h3>
</div>

<div class="container">
  <div class="row">
    <h2 class="center">Find A Pantry Near You</h2>
    <p class="center">Cooming Soon: Partnered RAAM pantries near you!</p>
    <nav style="margin: 1rem">
      <div class="nav-wrapper">
        <form
          action="https://www.google.com/maps/"
          method="get"
          name="searchform"
          target="_blank"
        >
          <div class="input-field">
            <input
              id="search"
              type="search"
              required
              autocomplete="on"
              class="white"
              name="q"
              placeholder="Search Maps"
              required="required"
              type="text"
            />
            <label class="label-icon" for="search"
              ><i class="material-icons">search</i></label
            >
            <i class="material-icons">close</i>
          </div>
        </form>
      </div>
    </nav>
  </div>
  <div class="row">
    <iframe
      style="border: solid orange 2px; width: 100%; height: 30rem"
      frameborder="0"
      style="border: 0"
      src="https://www.google.com/maps/embed/v1/search?key=AIzaSyBbVfxNU1etlk5nqVPX2Kcz_gs2dlq3P6Q&q=United+States"
      allowfullscreen
    >
    </iframe>
  </div>
</div>
<div class="container">
  <ul class="collapsible">
    <li>
      <div class="collapsible-header">
        <i class="material-icons">place</i>Indiana
      </div>
      <div class="collapsible-body">
        <span
          ><iframe
            style="border: solid orange 2px; width: 100%; height: 30rem"
            frameborder="0"
            style="border: 0"
            src="https://www.google.com/maps/embed/v1/search?key=AIzaSyBbVfxNU1etlk5nqVPX2Kcz_gs2dlq3P6Q&q=food+pantry+in+indiana"
            allowfullscreen
          >
          </iframe
        ></span>
      </div>
    </li>
    <li>
      <div class="collapsible-header">
        <i class="material-icons">place</i>Texas
      </div>
      <div class="collapsible-body">
        <span
          ><iframe
            style="border: solid orange 2px; width: 100%; height: 30rem"
            frameborder="0"
            style="border: 0"
            src="https://www.google.com/maps/embed/v1/search?key=AIzaSyBbVfxNU1etlk5nqVPX2Kcz_gs2dlq3P6Q&q=food+pantry+in+texas"
            allowfullscreen
          >
          </iframe
        ></span>
      </div>
    </li>
    <li>
      <div class="collapsible-header">
        <i class="material-icons">place</i>California
      </div>
      <div class="collapsible-body">
        <span
          ><iframe
            style="border: solid orange 2px; width: 100%; height: 30rem"
            frameborder="0"
            style="border: 0"
            src="https://www.google.com/maps/embed/v1/search?key=AIzaSyBbVfxNU1etlk5nqVPX2Kcz_gs2dlq3P6Q&q=food+pantry+in+california"
            allowfullscreen
          >
          </iframe
        ></span>
      </div>
    </li>
    <li>
      <div class="collapsible-header">
        <i class="material-icons">place</i>Georgia
      </div>
      <div class="collapsible-body">
        <span
          ><iframe
            style="border: solid orange 2px; width: 100%; height: 30rem"
            frameborder="0"
            style="border: 0"
            src="https://www.google.com/maps/embed/v1/search?key=AIzaSyBbVfxNU1etlk5nqVPX2Kcz_gs2dlq3P6Q&q=food+pantry+in+georgia"
            allowfullscreen
          >
          </iframe
        ></span>
      </div>
    </li>
    <li>
      <div class="collapsible-header">
        <i class="material-icons">place</i>New York
      </div>
      <div class="collapsible-body">
        <span
          ><iframe
            style="border: solid orange 2px; width: 100%; height: 30rem"
            frameborder="0"
            style="border: 0"
            src="https://www.google.com/maps/embed/v1/search?key=AIzaSyBbVfxNU1etlk5nqVPX2Kcz_gs2dlq3P6Q&q=food+pantry+in+newyork"
            allowfullscreen
          >
          </iframe
        ></span>
      </div>
    </li>
    <li>
      <div class="collapsible-header">
        <i class="material-icons">place</i>Illinois
      </div>
      <div class="collapsible-body">
        <span
          ><iframe
            style="border: solid orange 2px; width: 100%; height: 30rem"
            frameborder="0"
            style="border: 0"
            src="https://www.google.com/maps/embed/v1/search?key=AIzaSyBbVfxNU1etlk5nqVPX2Kcz_gs2dlq3P6Q&q=food+pantry+in+illinois"
            allowfullscreen
          >
          </iframe
        ></span>
      </div>
    </li>
    <li>
      <div class="collapsible-header">
        <i class="material-icons">place</i>Florida
      </div>
      <div class="collapsible-body">
        <span
          ><iframe
            style="border: solid orange 2px; width: 100%; height: 30rem"
            frameborder="0"
            style="border: 0"
            src="https://www.google.com/maps/embed/v1/search?key=AIzaSyBbVfxNU1etlk5nqVPX2Kcz_gs2dlq3P6Q&q=food+pantry+in+florida"
            allowfullscreen
          >
          </iframe
        ></span>
      </div>
    </li>
  </ul>
</div>

<script>
  $(document).ready(function () {
    $(".collapsible").collapsible();
  });
</script>

{% endblock %}

main_app/templates/main_app/food_comfirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1> Delete Food </h1>

<h4>
    Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'foods_detail' object.id %}" style="text-decoration: none; color: black;">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/food_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <h1>Foods</h1>

  <div class="row">
    <div class="col s6 col-offset-3">
      <div class="card">
        <div class="card-content">
          <span class="card-title orange-text darken-2">{{ food.name }}</span>
          <p>Description:{{ food.description }}</p>
          <p>Quantity:{{ food.quantity }}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'foods_update' food.id %}">Edit</a>
          <a href="{% url 'foods_delete' food.id %}">Delete</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/food_form.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  {% if object %}
  <h1>Update {{ object.name }}</h1>
  {% else %}
  <h1>Add Food</h1>
  {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table}}
    </table>
    <input type="submit" value="Update" class="btn green darken-2" />
  </form>
</div>
{% endblock %}

main_app/templates/main_app/food_list.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>Foods List</h1>

  {% for food in food_list %}
  <div class="card">
    <a
      href="{% url 'foods_detail' food.id %}"
      style="text-decoration: none; color: black"
    >
      <div class="card-content">
        <div class="row">
          <div class="col s4">
            <span class="card-title orange-text darken-2">{{ food.name }}</span>
            <p>Quantity: {{ food.quantity }}</p>
            <p>Description: {{ food.description }}</p>
          </div>
          <div class="col s4"></div>
          <div class="col s4">
            <img
              style="width: 50%"
              src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxzn6H0BMNBXR-rjTTMZdJ3mxS4AgkAE8FFg&usqp=CAU"
              alt="fooditem"
              srcset=""
            />
          </div>
        </div>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}

main_app/templates/main_app/pantry_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<h1>Delete Pantry</h1>

<h4>
    Are you sure you want to delete <span class="orange-text">{{ object.name }}</span>?
</h4>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Delete">
    <a class="btn green darken-1" href="{% url 'detail' object.id %}">Cancel</a>
</form>
</div>
{% endblock %}

main_app/templates/main_app/pantry_form.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  {% if object %}
  <h1>Update {{ object.name }}</h1>
  {% else %}
  <h1>Add Pantry</h1>
  {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table}}
    </table>
    <input type="submit" value="Submit!" class="btn green darken-2" />
  </form>
</div>
{% endblock %}

main_app/templates/pantries/detail.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>Details of Pantry</h1>

  <div class="card">
    <div class="card-content">
      <span class="card-title orange-text darken-2">{{ pantry.name }}</span>
      <p>Info: {{ pantry.description }}</p>
      <p>Location: {{ pantry.location }}</p>
    </div>
    <div class="card-action">
      {% if user.is_authenticated %}
      <a href="{% url 'pantries_update' pantry.id %}"> Edit </a>
      <a href="{% url 'pantries_delete' pantry.id %}"> Delete </a>
      {% else %} {% endif %}
    </div>
  </div>
  <h2>Schedule Pick up/ Drop Off</h2>
  <div class="card">
    <div class="col s6">
      <div class="card-content">
      <form action="{% url 'add_schedule' pantry.id %}" method="post">
        {% csrf_token %} {{ schedule_form.as_p }} {% if user.is_authenticated %}
        <input class="btn green" type="submit" value="Add schedule" />
        {% else %} {% endif %}
      </form>
    </div>
    <div class="card-action">
      <table class="striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>schedule</th>
          </tr>
        </thead>
        <tbody>
          {% for schedule in pantry.schedule_set.all %}
          <tr>
            <td>{{ schedule.date }}</td>
            <td>
              {{ schedule.get_service_display }}
              <button style="margin: 1rem;" class="btn green darken-2">Update</button>
            <button class="btn red">Delete</button>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    </div>
  </div>
  <hr />
  <div class="row">
    <div class="col s6">
      <h3 class="">{{ pantry.name }} Inventory</h3>
      {% for food in pantry.foods.all %}
      {% if user.is_authenticated %}
      <a href="{% url 'foods_update' food.id %}" style="text-decoration: none; color: black;">
        {% else %} {% endif %}
        <div class="card">
          <div class="card-content">
            <span class="card-title orange-text darken-2">{{ food.name }}</span>
            <p>Description: {{ food.description }}</p>
            <p>Quantity: {{ food.quantity }}</p>
            <img
              style="width: 10%"
              src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxzn6H0BMNBXR-rjTTMZdJ3mxS4AgkAE8FFg&usqp=CAU"
              alt="fooditem"
              srcset=""
            />
            {% if user.is_authenticated %}
            <form
              action="{% url 'unassoc_food' pantry.id food.id %}"
              method="delete"
            >
              {% csrf_token %}
              <button type="submit" class="btn red">Remove</button>
            </form>
            {% else %} {% endif %}
          </div>
        </div>
        {% if user.is_authenticated %}
      </a>
      {% else %} {% endif %}
    
      {% endfor %}
    </div>
  </div>
  <hr />

  {% if user.is_authenticated %}

  <div class="col s6">
    <h3>Items Available To Add</h3>
    {% for food in foods %}
    <div class="card">
      <div class="card-content">
        <span class="card-title orange-text darken-2">{{ food.name }}</span>
        <p>Description: {{ food.description }}</p>
        <p>Quantity: {{ food.quantity }}</p>
        <img
              style="width: 10%"
              src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxzn6H0BMNBXR-rjTTMZdJ3mxS4AgkAE8FFg&usqp=CAU"
              alt="fooditem"
              srcset=""
            />
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_food' pantry.id food.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn green darken-2">
            Add To Pantry
          </button>
        </form>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %} {% endif %}
</div>
<script>
  const dateEl = document.getElementById("id_date");
  const selectEl = document.getElementById("id_service");

  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });

  M.FormSelect.init(selectEl);
</script>

{% endblock %}